// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsDWPDI7oQKygKEh5mgXV2JnhZs4-NVfM',
    appId: '1:868370461493:web:457d0538f22c8765bcd27c',
    messagingSenderId: '868370461493',
    projectId: 'bir-umma-clone',
    authDomain: 'bir-umma-clone.firebaseapp.com',
    storageBucket: 'bir-umma-clone.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtmNNrVWgbXzWCYaeEAVSa9k0E7Du-U7c',
    appId: '1:868370461493:android:166789f8c87f8296bcd27c',
    messagingSenderId: '868370461493',
    projectId: 'bir-umma-clone',
    storageBucket: 'bir-umma-clone.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDktuYyyN-jov2dZktUK_51O1wwc_1LZTQ',
    appId: '1:868370461493:ios:5edce89341190bcebcd27c',
    messagingSenderId: '868370461493',
    projectId: 'bir-umma-clone',
    storageBucket: 'bir-umma-clone.appspot.com',
    iosClientId: '868370461493-c4kso3eabc03ueoj1va8bs9lp7gnov8p.apps.googleusercontent.com',
    iosBundleId: 'com.example.birUrmaClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDktuYyyN-jov2dZktUK_51O1wwc_1LZTQ',
    appId: '1:868370461493:ios:82fdf1ab31a83868bcd27c',
    messagingSenderId: '868370461493',
    projectId: 'bir-umma-clone',
    storageBucket: 'bir-umma-clone.appspot.com',
    iosClientId: '868370461493-8fdferhhll015p3uusciuhs7r9t8f0s9.apps.googleusercontent.com',
    iosBundleId: 'com.example.birUrmaClone.RunnerTests',
  );
}
